language: c

compiler:
    - gcc
    - clang

jobs:
  include:
    - script:
        - make
        - make test
    - stage: deploy
        script:
            - echo "start deploy..."
    
after_success:
    - bash <(curl -s https://codecov.io/bash)
