language: c

compiler:
    - gcc
    - clang

jobs:
  include:
    - stage: deploy
      script:
        - echo "start deploy..."
    
script: 
    - make && make test

after_success:
    - bash <(curl -s https://codecov.io/bash)
