language: c

compiler: 
    - gcc
    - clang
    
stage: build
name: "build and test."
script: 
  - make && make test
after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: deploy
      name: "deploy first test."
      script:
        - echo "start deploy..."
        
notifications:
  email:
    on_success: always