language: c

jobs:
  include:
    - stage: build
      name: "build and test."
      compiler:
        - gcc
        - clang
      script: 
        - make && make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      name: "deploy first test."
      script:
        - echo "start deploy..."