language: c

jobs:
  include:
    - stage: build
      compiler:
        - gcc
        - clang
      script:
        - make && make test
    - stage: deploy
      script:
        - echo "start deploy..."
    
script: true

after_success:
    - bash <(curl -s https://codecov.io/bash)
